{
  'name': 'ToDoListAPI',
  'repository_url': 'demo-ctt-todolistapi',
  'sut_tosca_path': 'todolist.csar',
  'ti_tosca_path': 'deploymentTestAgent.csar',
  'ti_inputs_path': 'inputs.yaml',
  'result_destination_path': '/tmp/results.zip',
  'test_id': 'deploymentTest_01',
}