# coding: utf-8

# flake8: noqa
"""
    RADON CTT Server API

    This is API of the RADON Continuous Testing Tool (CTT) Server: <a href=\"https://github.com/radon-h2020/radon-ctt\">https://github.com/radon-h2020/radon-ctt<a/>  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.deployment import Deployment
from swagger_client.models.execution import Execution
from swagger_client.models.post_deployment import POSTDeployment
from swagger_client.models.post_execution import POSTExecution
from swagger_client.models.post_project import POSTProject
from swagger_client.models.post_result import POSTResult
from swagger_client.models.post_test_artifact import POSTTestArtifact
from swagger_client.models.project import Project
from swagger_client.models.result import Result
from swagger_client.models.test_artifact import TestArtifact
