# coding: utf-8

"""
    RADON CTT Server API

    This is API of the RADON Continuous Testing Tool (CTT) Server: <a href=\"https://github.com/radon-h2020/radon-ctt\">https://github.com/radon-h2020/radon-ctt<a/>  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class POSTDeployment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'testartifact_uuid': 'str'
    }

    attribute_map = {
        'testartifact_uuid': 'testartifact_uuid'
    }

    def __init__(self, testartifact_uuid=None):  # noqa: E501
        """POSTDeployment - a model defined in Swagger"""  # noqa: E501
        self._testartifact_uuid = None
        self.discriminator = None
        self.testartifact_uuid = testartifact_uuid

    @property
    def testartifact_uuid(self):
        """Gets the testartifact_uuid of this POSTDeployment.  # noqa: E501


        :return: The testartifact_uuid of this POSTDeployment.  # noqa: E501
        :rtype: str
        """
        return self._testartifact_uuid

    @testartifact_uuid.setter
    def testartifact_uuid(self, testartifact_uuid):
        """Sets the testartifact_uuid of this POSTDeployment.


        :param testartifact_uuid: The testartifact_uuid of this POSTDeployment.  # noqa: E501
        :type: str
        """
        if testartifact_uuid is None:
            raise ValueError("Invalid value for `testartifact_uuid`, must not be `None`")  # noqa: E501

        self._testartifact_uuid = testartifact_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(POSTDeployment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, POSTDeployment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
