# coding: utf-8

"""
    RADON CTT Server API

    This is API of the RADON Continuous Testing Tool (CTT) Server: <a href=\"https://github.com/radon-h2020/radon-ctt\">https://github.com/radon-h2020/radon-ctt<a/>  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TestArtifactApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_testartifact(self, **kwargs):  # noqa: E501
        """Creates a test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_testartifact(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param POSTTestArtifact body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_testartifact_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_testartifact_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_testartifact_with_http_info(self, **kwargs):  # noqa: E501
        """Creates a test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_testartifact_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param POSTTestArtifact body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_testartifact" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testartifact', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_testartifact_by_uuid(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Delete a test artifact  # noqa: E501

        Deletes the test artifact with the given UUID and all elements depending on it  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_testartifact_by_uuid(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to delete (required)
        :return: TestArtifact
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
            return data

    def delete_testartifact_by_uuid_with_http_info(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Delete a test artifact  # noqa: E501

        Deletes the test artifact with the given UUID and all elements depending on it  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_testartifact_by_uuid_with_http_info(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to delete (required)
        :return: TestArtifact
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['testartifact_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_testartifact_by_uuid" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'testartifact_uuid' is set
        if ('testartifact_uuid' not in params or
                params['testartifact_uuid'] is None):
            raise ValueError("Missing the required parameter `testartifact_uuid` when calling `delete_testartifact_by_uuid`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'testartifact_uuid' in params:
            path_params['testartifact_uuid'] = params['testartifact_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testartifact/{testartifact_uuid}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TestArtifact',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def download_testartifact_by_uuid(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Downloads the generated test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_testartifact_by_uuid(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to download (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.download_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.download_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
            return data

    def download_testartifact_by_uuid_with_http_info(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Downloads the generated test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_testartifact_by_uuid_with_http_info(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to download (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['testartifact_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method download_testartifact_by_uuid" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'testartifact_uuid' is set
        if ('testartifact_uuid' not in params or
                params['testartifact_uuid'] is None):
            raise ValueError("Missing the required parameter `testartifact_uuid` when calling `download_testartifact_by_uuid`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'testartifact_uuid' in params:
            path_params['testartifact_uuid'] = params['testartifact_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testartifact/{testartifact_uuid}/download', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_testartifact_by_uuid(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Retrieve a test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_testartifact_by_uuid(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to return (required)
        :return: TestArtifact
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.get_testartifact_by_uuid_with_http_info(testartifact_uuid, **kwargs)  # noqa: E501
            return data

    def get_testartifact_by_uuid_with_http_info(self, testartifact_uuid, **kwargs):  # noqa: E501
        """Retrieve a test artifact  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_testartifact_by_uuid_with_http_info(testartifact_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str testartifact_uuid: UUID of the test artifact to return (required)
        :return: TestArtifact
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['testartifact_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_testartifact_by_uuid" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'testartifact_uuid' is set
        if ('testartifact_uuid' not in params or
                params['testartifact_uuid'] is None):
            raise ValueError("Missing the required parameter `testartifact_uuid` when calling `get_testartifact_by_uuid`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'testartifact_uuid' in params:
            path_params['testartifact_uuid'] = params['testartifact_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testartifact/{testartifact_uuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='TestArtifact',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_testartifacts(self, **kwargs):  # noqa: E501
        """Get all test artifacts  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_testartifacts(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[TestArtifact]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_testartifacts_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_testartifacts_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_testartifacts_with_http_info(self, **kwargs):  # noqa: E501
        """Get all test artifacts  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_testartifacts_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[TestArtifact]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_testartifacts" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testartifact', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TestArtifact]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
